### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by NikoZazza** [xionbig/SignShop#11]
- [X] Could not pass event 'pocketmine\event\level\LevelLoadEvent' #8 
- [X] Players can sell items even when they don't have them #7  
- [ ] PHP7.0
- [ ] Set the maximum number of signs that a player can create
- [ ] Call to a member function save() on null
- [ ] Call to a member function isEnabled() on null
- [ ] Call to a member function onDisable() on null
- [ ] Call to undefined method SignShop\Manager\MessageM...
- [ ] Add command /sign gift <amount> <player>
- [ ] Add command /sign tp <id_of_sign>, /sign list for the list of your signs and /sign tp <on|off> only on console.
- [ ] Add events
- [ ] Improve notifications
- [ ] Sell without having this Items #13 
- [ ] Improve the storage of data
- [ ] Add the possibility of extending the plugin<br>
  <strike>\- [ ] EssentialsPE Economy API</strike>

**Comment by NikoZazza** [comment]
The support of EssentialsPE will not be added because of the different methods of storage management, SignShop will not support EssentialPe otherwise it will cause problems for other plugin economy.
I would recommend using PocketMoney, Essentials and MassiveEconomy.
