### ISSUE TITLE
TODO-List

### ISSUE THREAD

**Issue by NikoZazza** [xionbig/SignShop#4]
- [x] make a todo list
- [x] bug "/sign empty glitch" #5
- [x] players are selling stuff with out the item in ther inventory #7

**Comment by xionbig** [comment]
- [ ] Bugfix /sign empty glitch #5

**Comment by YoungRichNigger9** [comment]
players are selling stuff with out the item in ther inventory
